package com.app.beepower;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beepower.proto

public final class Beepower {
  private Beepower() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PayloadOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes value = 1;
    boolean hasValue();
    com.google.protobuf.ByteString getValue();
    
    // optional bool test_flag = 10 [default = false];
    boolean hasTestFlag();
    boolean getTestFlag();
    
    // optional string clientId = 14 [default = ""];
    boolean hasClientId();
    String getClientId();
    
    // optional int32 messageId = 15 [default = 0];
    boolean hasMessageId();
    int getMessageId();
  }
  public static final class Payload extends
      com.google.protobuf.GeneratedMessage
      implements PayloadOrBuilder {
    // Use Payload.newBuilder() to construct.
    private Payload(Builder builder) {
      super(builder);
    }
    private Payload(boolean noInit) {}
    
    private static final Payload defaultInstance;
    public static Payload getDefaultInstance() {
      return defaultInstance;
    }
    
    public Payload getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Beepower.internal_static_Payload_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Beepower.internal_static_Payload_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    
    // optional bool test_flag = 10 [default = false];
    public static final int TEST_FLAG_FIELD_NUMBER = 10;
    private boolean testFlag_;
    public boolean hasTestFlag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getTestFlag() {
      return testFlag_;
    }
    
    // optional string clientId = 14 [default = ""];
    public static final int CLIENTID_FIELD_NUMBER = 14;
    private java.lang.Object clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 messageId = 15 [default = 0];
    public static final int MESSAGEID_FIELD_NUMBER = 15;
    private int messageId_;
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMessageId() {
      return messageId_;
    }
    
    private void initFields() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      testFlag_ = false;
      clientId_ = "";
      messageId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(10, testFlag_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(14, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(15, messageId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, testFlag_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, messageId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Beepower.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Beepower.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Beepower.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Beepower.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Beepower.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Beepower.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Beepower.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Beepower.Payload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Beepower.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Beepower.internal_static_Payload_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Beepower.internal_static_Payload_fieldAccessorTable;
      }
      
      // Construct using Beepower.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        testFlag_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Beepower.Payload.getDescriptor();
      }
      
      public Beepower.Payload getDefaultInstanceForType() {
        return Beepower.Payload.getDefaultInstance();
      }
      
      public Beepower.Payload build() {
        Beepower.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Beepower.Payload buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Beepower.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Beepower.Payload buildPartial() {
        Beepower.Payload result = new Beepower.Payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.testFlag_ = testFlag_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageId_ = messageId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Beepower.Payload) {
          return mergeFrom((Beepower.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Beepower.Payload other) {
        if (other == Beepower.Payload.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasTestFlag()) {
          setTestFlag(other.getTestFlag());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000002;
              testFlag_ = input.readBool();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000004;
              clientId_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000008;
              messageId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes value = 1;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      
      // optional bool test_flag = 10 [default = false];
      private boolean testFlag_ ;
      public boolean hasTestFlag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getTestFlag() {
        return testFlag_;
      }
      public Builder setTestFlag(boolean value) {
        bitField0_ |= 0x00000002;
        testFlag_ = value;
        onChanged();
        return this;
      }
      public Builder clearTestFlag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testFlag_ = false;
        onChanged();
        return this;
      }
      
      // optional string clientId = 14 [default = ""];
      private java.lang.Object clientId_ = "";
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      void setClientId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
      }
      
      // optional int32 messageId = 15 [default = 0];
      private int messageId_ ;
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMessageId() {
        return messageId_;
      }
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000008;
        messageId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Payload)
    }
    
    static {
      defaultInstance = new Payload(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Payload)
  }
  
  public interface BeeMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string topic = 1;
    boolean hasTopic();
    String getTopic();
    
    // optional .Payload payload = 2;
    boolean hasPayload();
    Beepower.Payload getPayload();
    Beepower.PayloadOrBuilder getPayloadOrBuilder();
    
    // optional .BeeMessage.MessageType message_type = 5 [default = PUBLISH];
    boolean hasMessageType();
    Beepower.BeeMessage.MessageType getMessageType();
    
    // optional int32 qos = 6 [default = 0];
    boolean hasQos();
    int getQos();
    
    // optional bool retain_flag = 7 [default = false];
    boolean hasRetainFlag();
    boolean getRetainFlag();
  }
  public static final class BeeMessage extends
      com.google.protobuf.GeneratedMessage
      implements BeeMessageOrBuilder {
    // Use BeeMessage.newBuilder() to construct.
    private BeeMessage(Builder builder) {
      super(builder);
    }
    private BeeMessage(boolean noInit) {}
    
    private static final BeeMessage defaultInstance;
    public static BeeMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public BeeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Beepower.internal_static_BeeMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Beepower.internal_static_BeeMessage_fieldAccessorTable;
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      PUBLISH(0, 0),
      SUBSCRIBE(1, 1),
      UNSUBSCRIBE(2, 2),
      ;
      
      public static final int PUBLISH_VALUE = 0;
      public static final int SUBSCRIBE_VALUE = 1;
      public static final int UNSUBSCRIBE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return PUBLISH;
          case 1: return SUBSCRIBE;
          case 2: return UNSUBSCRIBE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Beepower.BeeMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MessageType[] VALUES = {
        PUBLISH, SUBSCRIBE, UNSUBSCRIBE, 
      };
      
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:BeeMessage.MessageType)
    }
    
    private int bitField0_;
    // required string topic = 1;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private java.lang.Object topic_;
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          topic_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .Payload payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private Beepower.Payload payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public Beepower.Payload getPayload() {
      return payload_;
    }
    public Beepower.PayloadOrBuilder getPayloadOrBuilder() {
      return payload_;
    }
    
    // optional .BeeMessage.MessageType message_type = 5 [default = PUBLISH];
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 5;
    private Beepower.BeeMessage.MessageType messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Beepower.BeeMessage.MessageType getMessageType() {
      return messageType_;
    }
    
    // optional int32 qos = 6 [default = 0];
    public static final int QOS_FIELD_NUMBER = 6;
    private int qos_;
    public boolean hasQos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getQos() {
      return qos_;
    }
    
    // optional bool retain_flag = 7 [default = false];
    public static final int RETAIN_FLAG_FIELD_NUMBER = 7;
    private boolean retainFlag_;
    public boolean hasRetainFlag() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getRetainFlag() {
      return retainFlag_;
    }
    
    private void initFields() {
      topic_ = "";
      payload_ = Beepower.Payload.getDefaultInstance();
      messageType_ = Beepower.BeeMessage.MessageType.PUBLISH;
      qos_ = 0;
      retainFlag_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTopicBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, payload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(5, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, qos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(7, retainFlag_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTopicBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, payload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, qos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, retainFlag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Beepower.BeeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Beepower.BeeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Beepower.BeeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Beepower.BeeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Beepower.BeeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Beepower.BeeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Beepower.BeeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Beepower.internal_static_BeeMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Beepower.internal_static_BeeMessage_fieldAccessorTable;
      }
      
      // Construct using Beepower.BeeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPayloadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (payloadBuilder_ == null) {
          payload_ = Beepower.Payload.getDefaultInstance();
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = Beepower.BeeMessage.MessageType.PUBLISH;
        bitField0_ = (bitField0_ & ~0x00000004);
        qos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        retainFlag_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Beepower.BeeMessage.getDescriptor();
      }
      
      public Beepower.BeeMessage getDefaultInstanceForType() {
        return Beepower.BeeMessage.getDefaultInstance();
      }
      
      public Beepower.BeeMessage build() {
        Beepower.BeeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Beepower.BeeMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Beepower.BeeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Beepower.BeeMessage buildPartial() {
        Beepower.BeeMessage result = new Beepower.BeeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.qos_ = qos_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.retainFlag_ = retainFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Beepower.BeeMessage) {
          return mergeFrom((Beepower.BeeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Beepower.BeeMessage other) {
        if (other == Beepower.BeeMessage.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          setTopic(other.getTopic());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasQos()) {
          setQos(other.getQos());
        }
        if (other.hasRetainFlag()) {
          setRetainFlag(other.getRetainFlag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTopic()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              topic_ = input.readBytes();
              break;
            }
            case 18: {
              Beepower.Payload.Builder subBuilder = Beepower.Payload.newBuilder();
              if (hasPayload()) {
                subBuilder.mergeFrom(getPayload());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPayload(subBuilder.buildPartial());
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              Beepower.BeeMessage.MessageType value = Beepower.BeeMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                messageType_ = value;
              }
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              qos_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              retainFlag_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string topic = 1;
      private java.lang.Object topic_ = "";
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTopic(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      void setTopic(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
      }
      
      // optional .Payload payload = 2;
      private Beepower.Payload payload_ = Beepower.Payload.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Beepower.Payload, Beepower.Payload.Builder, Beepower.PayloadOrBuilder> payloadBuilder_;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public Beepower.Payload getPayload() {
        if (payloadBuilder_ == null) {
          return payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      public Builder setPayload(Beepower.Payload value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPayload(
          Beepower.Payload.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePayload(Beepower.Payload value) {
        if (payloadBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              payload_ != Beepower.Payload.getDefaultInstance()) {
            payload_ =
              Beepower.Payload.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = Beepower.Payload.getDefaultInstance();
          onChanged();
        } else {
          payloadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public Beepower.Payload.Builder getPayloadBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      public Beepower.PayloadOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Beepower.Payload, Beepower.Payload.Builder, Beepower.PayloadOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Beepower.Payload, Beepower.Payload.Builder, Beepower.PayloadOrBuilder>(
                  payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }
      
      // optional .BeeMessage.MessageType message_type = 5 [default = PUBLISH];
      private Beepower.BeeMessage.MessageType messageType_ = Beepower.BeeMessage.MessageType.PUBLISH;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Beepower.BeeMessage.MessageType getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(Beepower.BeeMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageType_ = Beepower.BeeMessage.MessageType.PUBLISH;
        onChanged();
        return this;
      }
      
      // optional int32 qos = 6 [default = 0];
      private int qos_ ;
      public boolean hasQos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getQos() {
        return qos_;
      }
      public Builder setQos(int value) {
        bitField0_ |= 0x00000008;
        qos_ = value;
        onChanged();
        return this;
      }
      public Builder clearQos() {
        bitField0_ = (bitField0_ & ~0x00000008);
        qos_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool retain_flag = 7 [default = false];
      private boolean retainFlag_ ;
      public boolean hasRetainFlag() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getRetainFlag() {
        return retainFlag_;
      }
      public Builder setRetainFlag(boolean value) {
        bitField0_ |= 0x00000010;
        retainFlag_ = value;
        onChanged();
        return this;
      }
      public Builder clearRetainFlag() {
        bitField0_ = (bitField0_ & ~0x00000010);
        retainFlag_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BeeMessage)
    }
    
    static {
      defaultInstance = new BeeMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BeeMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BeeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BeeMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016beepower.proto\"\\\n\007Payload\022\r\n\005value\030\001 \001" +
      "(\014\022\030\n\ttest_flag\030\n \001(\010:\005false\022\022\n\010clientId" +
      "\030\016 \001(\t:\000\022\024\n\tmessageId\030\017 \001(\005:\0010\"\326\001\n\nBeeMe" +
      "ssage\022\r\n\005topic\030\001 \002(\t\022\031\n\007payload\030\002 \001(\0132\010." +
      "Payload\0226\n\014message_type\030\005 \001(\0162\027.BeeMessa" +
      "ge.MessageType:\007PUBLISH\022\016\n\003qos\030\006 \001(\005:\0010\022" +
      "\032\n\013retain_flag\030\007 \001(\010:\005false\":\n\013MessageTy" +
      "pe\022\013\n\007PUBLISH\020\000\022\r\n\tSUBSCRIBE\020\001\022\017\n\013UNSUBS" +
      "CRIBE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Payload_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Payload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Payload_descriptor,
              new java.lang.String[] { "Value", "TestFlag", "ClientId", "MessageId", },
              Beepower.Payload.class,
              Beepower.Payload.Builder.class);
          internal_static_BeeMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BeeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BeeMessage_descriptor,
              new java.lang.String[] { "Topic", "Payload", "MessageType", "Qos", "RetainFlag", },
              Beepower.BeeMessage.class,
              Beepower.BeeMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
